deployment:
  tasks:
    - export DEPLOYPATH=/home3/alexryan/public_html/PruebaGo/  # Ajusta la ruta de despliegue
    - /bin/cp -r * $DEPLOYPATH
    - /home3/alexryan/public_html/PruebaGo/PruebaGo.exe 